name: Push Event Workflow

on: push

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
    - name : Checkout code
      uses : actions/checkout@v4

    - name : Install packages
      run : pip install -r requirements.txt

    - name : Run tests
      run : cd src && PYTHONPATH="$(pwd)" && python -m unittest tests/*